name: Build the site using webpack

on: 
  push: main

jobs:
  build-site:
    runs-on: ubuntu-latest
    name: Build site with webpack 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install npm
        uses: npm ci

      - name: Build
        run: |
          npm run build

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist
